version: "3.7"
services:
  db:
    build:
      context: ./db
    image: db
    container_name: fs-db
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  db-admin:
    depends_on:
      - db
    image: mongo-express:latest
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_PORT: 27017
  bff:
    depends_on:
      - db
    build:
      context: ./bff
    image: bff
    environment:
      PROFILE: dev
    ports:
      - '5000:5000'
  spa:
    depends_on:
      - bff
    build:
      context: ./spa
    image: spa
    ports:
      - '8080:8080'
