version: "3.7"
services:
  db:
    build:
      context: ./db
    image: db
    ports:
      - "1433:1433"
  bff:
    build:
      context: ./bff
    image: bff
    ports:
      - "5000:5000"
  spa:
    build:
      context: ./spa
    image: spa
    ports:
      - "8080:8080"
