version: "3.7"
services:
  db:
    build:
      context: ./db
    image: fs-db
    container_name: fs-db
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
