name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose build
    - name: Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag
      run: docker tag db docker.pkg.github.com/makimenko/fs/db:${{ github.run_id }}
    - name: Push
      run: docker push docker.pkg.github.com/makimenko/fs/db:${{ github.run_id }}
