name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose build
    - name: Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tag
      run: docker tag db docker.pkg.github.com/makimenko/fs/db:${{ github.run_number }}
    - name: Push
      run: docker push docker.pkg.github.com/makimenko/fs/db:${{ github.run_number }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEazN }}
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV_DB }}
    - name: Deploy
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: makimenko-fs-dev
        dns-name-label: makimenko-fs-dev-app-db.azurewebsites.net
        image: docker.pkg.github.com/makimenko/fs/db:${{ github.run_number }}
        name: db